const CONFIG = {
  MEMBERS: [
    { id: 'jjw', name: 'JJW', color: '#58a6ff' },
    { id: 'nym', name: 'NYM', color: '#f78166' },
    // 새 멤버 추가: { id: 'abc', name: 'ABC', color: '#7ee787' }
  ],

  PROBLEMS: [
    { id: 'q01_babbling1', name: '옹알이 (1)', rate: 38, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120956' },
    { id: 'q02_parallel', name: '평행', rate: 55, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120875' },
    { id: 'q03_overlapping_segments', name: '겹치는 선분의 길이', rate: 62, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120876' },
    { id: 'q04_fraction_addition', name: '분수의 덧셈', rate: 63, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120808' },
    { id: 'q05_safe_zone', name: '안전지대', rate: 64, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120866' },
    { id: 'q06_consecutive_sum', name: '연속된 수의 합', rate: 67, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120923' },
    { id: 'q07_next_number', name: '다음에 올 숫자', rate: 68, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120924' },
    { id: 'q08_find_mode', name: '최빈값 구하기', rate: 71, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120812' },
    { id: 'q09_ox_quiz', name: 'OX퀴즈', rate: 71, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120907' },
    { id: 'q10_unusual_sort', name: '특이한 정렬', rate: 74, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120880' },
    { id: 'q11_polynomial_addition', name: '다항식 더하기', rate: 74, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120863' },
    { id: 'q12_finite_decimal', name: '유한소수 판별하기', rate: 75, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120878' },
    { id: 'q13_cursed_number3', name: '저주의 숫자 3', rate: 76, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120871' },
    { id: 'q14_string_shift', name: '문자열 밀기', rate: 76, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120921' },
    { id: 'q15_chicken_coupon', name: '치킨 쿠폰', rate: 77, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120884' },
    { id: 'q16_ranking', name: '등수 매기기', rate: 77, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120882' },
    { id: 'q17_alien_dictionary', name: '외계어 사전', rate: 78, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120869' },
    { id: 'q18_login_success', name: '로그인 성공?', rate: 78, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120883' },
    { id: 'q19_rectangle_area', name: '직사각형 넓이 구하기', rate: 78, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120860' },
    { id: 'q20_character_coordinate', name: '캐릭터의 좌표', rate: 79, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120861' },
    { id: 'q21_paper_cutting', name: '종이 자르기', rate: 79, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120922' },
    { id: 'q22_remove_vowels', name: '모음이 싫어요', rate: 82, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120849' },
    { id: 'q23_triangle_condition2', name: '삼각형의 완성조건 (2)', rate: 82, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120868' },
    { id: 'q24_marble_combinations', name: '구슬을 나누는 경우의 수', rate: 82, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120840' },
    { id: 'q25_string_calculation', name: '문자열 계산하기', rate: 83, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120902' },
    { id: 'q26_ball_throwing', name: '공 던지기', rate: 83, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120843' },
    { id: 'q27_binary_addition', name: '이진수 더하기', rate: 83, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120885' },
    { id: 'q28_prime_factorization', name: '소인수분해', rate: 84, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120852' },
    { id: 'q29_slice_to_array', name: '잘라서 배열로 저장하기', rate: 85, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120913' },
    { id: 'q30_ctrl_z', name: '컨트롤 제트', rate: 85, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120853' },
    { id: 'q31_morse_code1', name: '모스부호 (1)', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120838' },
    { id: 'q32_make_b_from_a', name: 'A로 B 만들기', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120886' },
    { id: 'q33_count_k', name: 'k의 개수', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120887' },
    { id: 'q34_unique_char', name: '한 번만 등장한 문자', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120896' },
    { id: 'q35_hidden_number_sum2', name: '숨어있는 숫자의 덧셈 (2)', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120864' },
    { id: 'q36_count_seven', name: '7의 개수', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120912' },
    { id: 'q37_medical_order', name: '진료순서 정하기', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120835' },
    { id: 'q38_closest_number', name: '가까운 수', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120890' },
    { id: 'q39_factorial', name: '팩토리얼', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120848' },
    { id: 'q40_find_composite', name: '합성수 찾기', rate: 87, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120846' },
    { id: 'q41_remove_duplicates', name: '중복된 문자 제거', rate: 87, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120888' },
    { id: 'q42_make_2d_array', name: '2차원으로 만들기', rate: 87, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120842' },
    { id: 'q43_sharing_pizza2', name: '피자 나눠 먹기 (2)', rate: 88, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120815' },
    { id: 'q44_alien_planet_age', name: '외계행성의 나이', rate: 88, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120834' },
    { id: 'q45_rotate_array', name: '배열 회전시키기', rate: 88, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120844' },
    { id: 'q46_count_duplicates', name: '중복된 숫자 개수', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120583' },
    { id: 'q47_find_median', name: '중앙값 구하기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120811' },
    { id: 'q48_clothing_discount', name: '옷가게 할인 받기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120818' },
    { id: 'q49_right_triangle', name: '직각삼각형 출력하기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120823' },
    { id: 'q50_ant_army', name: '개미 군단', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120837' },
    { id: 'q51_rock_paper_scissors', name: '가위 바위 보', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120839' },
    { id: 'q52_count_dice', name: '주사위의 개수', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120845' },
    { id: 'q53_sort_string1', name: '문자열 정렬하기 (1)', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120850' },
    { id: 'q54_max_product2', name: '최댓값 만들기 (2)', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120862' },
    { id: 'q55_decode_cipher', name: '암호 해독', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120892' },
    { id: 'q56_swap_index', name: '인덱스 바꾸기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120895' },
    { id: 'q57_find_divisors', name: '약수 구하기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120897' },
    { id: 'q58_sort_string2', name: '문자열 정렬하기 (2)', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120911' },
    { id: 'q59_find_number', name: '숫자 찾기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120904' },
    { id: 'q60_369_game', name: '369게임', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120891' },
  ],
};
