export interface Problem {
  id: string;
  name: string;
  rate: number;
  url: string;
  level: number;
}

const LV0_PROBLEMS_RAW: Omit<Problem, 'level'>[] = [
  { id: 'q01_babbling1', name: '옹알이 (1)', rate: 38, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120956' },
  { id: 'q02_parallel', name: '평행', rate: 55, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120875' },
  { id: 'q03_overlapping_segments', name: '겹치는 선분의 길이', rate: 62, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120876' },
  { id: 'q04_fraction_addition', name: '분수의 덧셈', rate: 63, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120808' },
  { id: 'q05_safe_zone', name: '안전지대', rate: 64, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120866' },
  { id: 'q06_consecutive_sum', name: '연속된 수의 합', rate: 67, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120923' },
  { id: 'q07_next_number', name: '다음에 올 숫자', rate: 68, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120924' },
  { id: 'q08_find_mode', name: '최빈값 구하기', rate: 71, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120812' },
  { id: 'q09_ox_quiz', name: 'OX퀴즈', rate: 71, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120907' },
  { id: 'q10_unusual_sort', name: '특이한 정렬', rate: 74, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120880' },
  { id: 'q11_polynomial_addition', name: '다항식 더하기', rate: 74, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120863' },
  { id: 'q12_finite_decimal', name: '유한소수 판별하기', rate: 75, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120878' },
  { id: 'q13_cursed_number3', name: '저주의 숫자 3', rate: 76, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120871' },
  { id: 'q14_string_shift', name: '문자열 밀기', rate: 76, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120921' },
  { id: 'q15_chicken_coupon', name: '치킨 쿠폰', rate: 77, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120884' },
  { id: 'q16_ranking', name: '등수 매기기', rate: 77, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120882' },
  { id: 'q17_alien_dictionary', name: '외계어 사전', rate: 78, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120869' },
  { id: 'q18_login_success', name: '로그인 성공?', rate: 78, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120883' },
  { id: 'q19_rectangle_area', name: '직사각형 넓이 구하기', rate: 78, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120860' },
  { id: 'q20_character_coordinate', name: '캐릭터의 좌표', rate: 79, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120861' },
  { id: 'q21_paper_cutting', name: '종이 자르기', rate: 79, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120922' },
  { id: 'q22_remove_vowels', name: '모음이 싫어요', rate: 82, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120849' },
  { id: 'q23_triangle_condition2', name: '삼각형의 완성조건 (2)', rate: 82, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120868' },
  { id: 'q24_marble_combinations', name: '구슬을 나누는 경우의 수', rate: 82, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120840' },
  { id: 'q25_string_calculation', name: '문자열 계산하기', rate: 83, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120902' },
  { id: 'q26_ball_throwing', name: '공 던지기', rate: 83, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120843' },
  { id: 'q27_binary_addition', name: '이진수 더하기', rate: 83, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120885' },
  { id: 'q28_prime_factorization', name: '소인수분해', rate: 84, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120852' },
  { id: 'q29_slice_to_array', name: '잘라서 배열로 저장하기', rate: 85, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120913' },
  { id: 'q30_ctrl_z', name: '컨트롤 제트', rate: 85, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120853' },
  { id: 'q31_morse_code1', name: '모스부호 (1)', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120838' },
  { id: 'q32_make_b_from_a', name: 'A로 B 만들기', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120886' },
  { id: 'q33_count_k', name: 'k의 개수', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120887' },
  { id: 'q34_unique_char', name: '한 번만 등장한 문자', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120896' },
  { id: 'q35_hidden_number_sum2', name: '숨어있는 숫자의 덧셈 (2)', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120864' },
  { id: 'q36_count_seven', name: '7의 개수', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120912' },
  { id: 'q37_medical_order', name: '진료순서 정하기', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120835' },
  { id: 'q38_closest_number', name: '가까운 수', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120890' },
  { id: 'q39_factorial', name: '팩토리얼', rate: 86, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120848' },
  { id: 'q40_find_composite', name: '합성수 찾기', rate: 87, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120846' },
  { id: 'q41_remove_duplicates', name: '중복된 문자 제거', rate: 87, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120888' },
  { id: 'q42_make_2d_array', name: '2차원으로 만들기', rate: 87, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120842' },
  { id: 'q43_sharing_pizza2', name: '피자 나눠 먹기 (2)', rate: 88, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120815' },
  { id: 'q44_alien_planet_age', name: '외계행성의 나이', rate: 88, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120834' },
  { id: 'q45_rotate_array', name: '배열 회전시키기', rate: 88, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120844' },
  { id: 'q46_count_duplicates', name: '중복된 숫자 개수', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120583' },
  { id: 'q47_find_median', name: '중앙값 구하기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120811' },
  { id: 'q48_clothing_discount', name: '옷가게 할인 받기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120818' },
  { id: 'q49_right_triangle', name: '직각삼각형 출력하기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120823' },
  { id: 'q50_ant_army', name: '개미 군단', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120837' },
  { id: 'q51_rock_paper_scissors', name: '가위 바위 보', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120839' },
  { id: 'q52_count_dice', name: '주사위의 개수', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120845' },
  { id: 'q53_sort_string1', name: '문자열 정렬하기 (1)', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120850' },
  { id: 'q54_max_product2', name: '최댓값 만들기 (2)', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120862' },
  { id: 'q55_decode_cipher', name: '암호 해독', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120892' },
  { id: 'q56_swap_index', name: '인덱스 바꾸기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120895' },
  { id: 'q57_find_divisors', name: '약수 구하기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120897' },
  { id: 'q58_sort_string2', name: '문자열 정렬하기 (2)', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120911' },
  { id: 'q59_find_number', name: '숫자 찾기', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120904' },
  { id: 'q60_369_game', name: '369게임', rate: 89, url: 'https://school.programmers.co.kr/learn/courses/30/lessons/120891' },
];

const LV1_LIST_URL = 'https://school.programmers.co.kr/learn/challenges?levels=1';

const LV1_PROBLEMS_RAW: Omit<Problem, 'level'>[] = [
  // Page 1
  { id: 'l1_001', name: '노란색 신호등', rate: 30, url: LV1_LIST_URL },
  { id: 'l1_002', name: '수상한 단어들 스포 방지', rate: 26, url: LV1_LIST_URL },
  { id: 'l1_003', name: '택배 상자 꺼내기', rate: 37, url: LV1_LIST_URL },
  { id: 'l1_004', name: '유연근무제', rate: 50, url: LV1_LIST_URL },
  { id: 'l1_005', name: '[PCCP 기출문제] 1번 / 동영상 재생기', rate: 42, url: LV1_LIST_URL },
  { id: 'l1_006', name: '[PCCE 기출문제] 9번 / 지폐 접기', rate: 66, url: LV1_LIST_URL },
  { id: 'l1_007', name: '[PCCE 기출문제] 10번 / 공원', rate: 46, url: LV1_LIST_URL },
  { id: 'l1_008', name: '특정 형질을 가지는 대장균 찾기', rate: 48, url: LV1_LIST_URL },
  { id: 'l1_009', name: '가장 큰 물고기 10마리 구하기', rate: 76, url: LV1_LIST_URL },
  { id: 'l1_010', name: '한 해에 잡은 물고기 수 구하기', rate: 82, url: LV1_LIST_URL },
  { id: 'l1_011', name: '잡은 물고기 중 가장 큰 물고기의 길이 구하기', rate: 85, url: LV1_LIST_URL },
  { id: 'l1_012', name: '잡은 물고기의 평균 길이 구하기', rate: 83, url: LV1_LIST_URL },
  { id: 'l1_013', name: '친척이 없는 수 구하기', rate: 65, url: LV1_LIST_URL },
  { id: 'l1_014', name: 'Python 개발자 찾기', rate: 84, url: LV1_LIST_URL },
  { id: 'l1_015', name: '가장 많이 받은 선물', rate: 30, url: LV1_LIST_URL },
  { id: 'l1_016', name: '[PCCP 기출문제] 1번 / 동영상 잠기', rate: 45, url: LV1_LIST_URL },
  { id: 'l1_017', name: '[PCCE 기출문제] 9번 / 이웃한 칸', rate: 61, url: LV1_LIST_URL },
  { id: 'l1_018', name: '[PCCE 기출문제] 10번 / 데이터 분석', rate: 56, url: LV1_LIST_URL },
  { id: 'l1_019', name: '달리기 경주', rate: 51, url: LV1_LIST_URL },
  { id: 'l1_020', name: '추억 점수', rate: 71, url: LV1_LIST_URL },
  // Page 2
  { id: 'l1_021', name: '공원 산책', rate: 48, url: LV1_LIST_URL },
  { id: 'l1_022', name: '조건에 부합하는 중고거래 댓글 조회하기', rate: 71, url: LV1_LIST_URL },
  { id: 'l1_023', name: '바탕화면 정리', rate: 53, url: LV1_LIST_URL },
  { id: 'l1_024', name: '덧칠하기', rate: 66, url: LV1_LIST_URL },
  { id: 'l1_025', name: '대충 만든 자판', rate: 61, url: LV1_LIST_URL },
  { id: 'l1_026', name: '카드 뭉치', rate: 72, url: LV1_LIST_URL },
  { id: 'l1_027', name: '특정 옵션이 포함된 자동차 리스트 구하기', rate: 85, url: LV1_LIST_URL },
  { id: 'l1_028', name: '동물의 입양', rate: 61, url: LV1_LIST_URL },
  { id: 'l1_029', name: '자동차 대여 기록에서 장기/단기 대여 구분하기', rate: 79, url: LV1_LIST_URL },
  { id: 'l1_030', name: '평균 일일 대여 요금 구하기', rate: 85, url: LV1_LIST_URL },
  { id: 'l1_031', name: '개인정보 수집 유효기간', rate: 51, url: LV1_LIST_URL },
  { id: 'l1_032', name: '크기가 작은 부분 문자열', rate: 79, url: LV1_LIST_URL },
  { id: 'l1_033', name: '조건에 맞는 도시 리스트 출력하기', rate: 87, url: LV1_LIST_URL },
  { id: 'l1_034', name: '가장 가까운 같은 글자', rate: 75, url: LV1_LIST_URL },
  { id: 'l1_035', name: '문자열 나누기', rate: 67, url: LV1_LIST_URL },
  { id: 'l1_036', name: '명예의 전당 (1)', rate: 73, url: LV1_LIST_URL },
  { id: 'l1_037', name: '기사단원의 무기', rate: 68, url: LV1_LIST_URL },
  { id: 'l1_038', name: '과일 장수', rate: 65, url: LV1_LIST_URL },
  { id: 'l1_039', name: '푸드 파이트 대회', rate: 74, url: LV1_LIST_URL },
  { id: 'l1_040', name: '햄버거 만들기', rate: 59, url: LV1_LIST_URL },
  // Page 3
  { id: 'l1_041', name: '옹알이 (2)', rate: 65, url: LV1_LIST_URL },
  { id: 'l1_042', name: '과일로 만든 아이스크림 고르기', rate: 85, url: LV1_LIST_URL },
  { id: 'l1_043', name: '인기있는 아이스크림', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_044', name: '콜라 문제', rate: 73, url: LV1_LIST_URL },
  { id: 'l1_045', name: '흉부외과 또는 일반외과 의사 목록 출력하기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_046', name: '12세 이하인 여자 환자 목록 출력하기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_047', name: '삼총사', rate: 78, url: LV1_LIST_URL },
  { id: 'l1_048', name: '가장 비싼 상품 구하기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_049', name: '조건에 맞는 회원수 구하기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_050', name: '나이 정보가 없는 회원 수 구하기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_051', name: '숫자 짝꿍', rate: 58, url: LV1_LIST_URL },
  { id: 'l1_052', name: '경기도에 위치한 식품창고 목록 출력하기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_053', name: '강원도에 위치한 생산공장 목록 출력하기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_054', name: '성격 유형 검사하기', rate: 55, url: LV1_LIST_URL },
  { id: 'l1_055', name: '신고 결과 받기', rate: 42, url: LV1_LIST_URL },
  { id: 'l1_056', name: '나머지가 1이 되는 수 찾기', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_057', name: '최소직사각형', rate: 76, url: LV1_LIST_URL },
  { id: 'l1_058', name: '없는 숫자 더하기', rate: 87, url: LV1_LIST_URL },
  { id: 'l1_059', name: '부족한 금액 계산하기', rate: 84, url: LV1_LIST_URL },
  { id: 'l1_060', name: '숫자 문자열과 영단어', rate: 73, url: LV1_LIST_URL },
  // Page 4
  { id: 'l1_061', name: '약수의 개수와 덧셈', rate: 85, url: LV1_LIST_URL },
  { id: 'l1_062', name: '로또의 최고 순위와 최저 순위', rate: 60, url: LV1_LIST_URL },
  { id: 'l1_063', name: '입양 더하기', rate: 87, url: LV1_LIST_URL },
  { id: 'l1_064', name: '신규 아이디 추천', rate: 53, url: LV1_LIST_URL },
  { id: 'l1_065', name: '내적', rate: 85, url: LV1_LIST_URL },
  { id: 'l1_066', name: '3진법 뒤집기', rate: 77, url: LV1_LIST_URL },
  { id: 'l1_067', name: '두 개 뽑아서 더하기', rate: 74, url: LV1_LIST_URL },
  { id: 'l1_068', name: '키패드 누르기', rate: 54, url: LV1_LIST_URL },
  { id: 'l1_069', name: '크레인 인형뽑기 게임', rate: 55, url: LV1_LIST_URL },
  { id: 'l1_070', name: '최댓값 구하기', rate: 81, url: LV1_LIST_URL },
  { id: 'l1_071', name: '이름이 있는 동물의 아이디', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_072', name: '상위 n개 레코드', rate: 87, url: LV1_LIST_URL },
  { id: 'l1_073', name: '여러 기준으로 정렬하기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_074', name: '동물의 아이디와 이름', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_075', name: '이름이 없는 동물의 아이디', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_076', name: '어린 동물 찾기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_077', name: '아픈 동물 찾기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_078', name: '역순 정렬하기', rate: 91, url: LV1_LIST_URL },
  { id: 'l1_079', name: '모든 레코드 조회하기', rate: 84, url: LV1_LIST_URL },
  { id: 'l1_080', name: '실패율', rate: 63, url: LV1_LIST_URL },
  // Page 5
  { id: 'l1_081', name: '체육복', rate: 59, url: LV1_LIST_URL },
  { id: 'l1_082', name: '모의고사', rate: 67, url: LV1_LIST_URL },
  { id: 'l1_083', name: 'K번째 수', rate: 73, url: LV1_LIST_URL },
  { id: 'l1_084', name: '완주하지 못한 선수', rate: 60, url: LV1_LIST_URL },
  { id: 'l1_085', name: '[1차] 다트 게임', rate: 60, url: LV1_LIST_URL },
  { id: 'l1_086', name: '[1차] 비밀지도', rate: 71, url: LV1_LIST_URL },
  { id: 'l1_087', name: '예산', rate: 78, url: LV1_LIST_URL },
  { id: 'l1_088', name: '소수 만들기', rate: 64, url: LV1_LIST_URL },
  { id: 'l1_089', name: '직사각형 별찍기', rate: 80, url: LV1_LIST_URL },
  { id: 'l1_090', name: 'x만큼 간격이 있는 n개의 숫자', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_091', name: '행렬의 덧셈', rate: 81, url: LV1_LIST_URL },
  { id: 'l1_092', name: '핸드폰 번호 가리기', rate: 86, url: LV1_LIST_URL },
  { id: 'l1_093', name: '하샤드 수', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_094', name: '평균 구하기', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_095', name: '콜라츠 추측', rate: 66, url: LV1_LIST_URL },
  { id: 'l1_096', name: '최대공약수와 최소공배수', rate: 79, url: LV1_LIST_URL },
  { id: 'l1_097', name: '짝수와 홀수', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_098', name: '제일 작은 수 제거하기', rate: 85, url: LV1_LIST_URL },
  { id: 'l1_099', name: '정수 제곱근 판별', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_100', name: '정수 내림차순으로 배치하기', rate: 88, url: LV1_LIST_URL },
  // Page 6
  { id: 'l1_101', name: '자연수 뒤집어 배열로 만들기', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_102', name: '자릿수 더하기', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_103', name: '이상한 문자 만들기', rate: 77, url: LV1_LIST_URL },
  { id: 'l1_104', name: '약수의 합', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_105', name: '시저 암호', rate: 74, url: LV1_LIST_URL },
  { id: 'l1_106', name: '문자열을 정수로 바꾸기', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_107', name: '수박수박수박수박수박수?', rate: 85, url: LV1_LIST_URL },
  { id: 'l1_108', name: '소수 찾기', rate: 64, url: LV1_LIST_URL },
  { id: 'l1_109', name: '서울에서 김서방 찾기', rate: 86, url: LV1_LIST_URL },
  { id: 'l1_110', name: '문자열 다루기 기본', rate: 82, url: LV1_LIST_URL },
  { id: 'l1_111', name: '문자열 내림차순으로 배치하기', rate: 84, url: LV1_LIST_URL },
  { id: 'l1_112', name: '문자열 내 p와 y의 개수', rate: 87, url: LV1_LIST_URL },
  { id: 'l1_113', name: '문자열 내 마음대로 정렬하기', rate: 73, url: LV1_LIST_URL },
  { id: 'l1_114', name: '두 정수 사이의 합', rate: 88, url: LV1_LIST_URL },
  { id: 'l1_115', name: '나누어 떨어지는 숫자 배열', rate: 86, url: LV1_LIST_URL },
  { id: 'l1_116', name: '같은 숫자는 싫어', rate: 79, url: LV1_LIST_URL },
  { id: 'l1_117', name: '가운데 글자 가져오기', rate: 78, url: LV1_LIST_URL },
  { id: 'l1_118', name: '2016년', rate: 66, url: LV1_LIST_URL },
  { id: 'l1_119', name: '폰켓몬', rate: 69, url: LV1_LIST_URL },
];

export const PROBLEMS: Problem[] = [
  ...LV0_PROBLEMS_RAW.map(p => ({ ...p, level: 0 })),
  ...LV1_PROBLEMS_RAW.map(p => ({ ...p, level: 1 })),
];

// 레벨별로 그룹화된 문제 목록
export function groupByLevel(problems: Problem[]): Record<number, Problem[]> {
  const groups: Record<number, Problem[]> = {};
  for (const p of problems) {
    if (!groups[p.level]) groups[p.level] = [];
    groups[p.level].push(p);
  }
  return groups;
}

// 30문제 단위로 페이지 분할
export function paginateProblems(problems: Problem[], pageSize = 30): Problem[][] {
  const pages: Problem[][] = [];
  for (let i = 0; i < problems.length; i += pageSize) {
    pages.push(problems.slice(i, i + pageSize));
  }
  return pages;
}
